service: prekskills

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  stage: ${opt:stage, 'production'}
  serverless-offline:
    port: 3001

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-west-2
  environment: ${file(./env.json):${self:custom.stage}}
  profile: personal

functions:
  app:
    handler: handler.app
    role: arn:aws:iam::906585994835:role/lambda_s3_access
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
